sonar.projectKey=innote
sonar.projectName=Innote
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://172.26.5.10:9000
sonar.token=sqa_40bd9951770dc039fb871f2294dd8b987362be87
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true
